version: '3.9'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sichrplace-mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'YourStrong!Passw0rd'
      MSSQL_PID: 'Developer'
    ports:
      - '1433:1433'
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ['/bin/sh', '-c', '/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "SELECT 1"']
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
volumes:
  mssql_data:
    driver: local
